/* Generated By:JavaCC: Do not edit this line. NuevoParserConstants.java */
package uniandes.teolen.parserJavaCC.newParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NuevoParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int EXPONENCIAL = 9;
  /** RegularExpression Id. */
  int CONSTANT = 10;
  /** RegularExpression Id. */
  int DIGIT = 11;
  /** RegularExpression Id. */
  int COMPLEX = 12;
  /** RegularExpression Id. */
  int LETTER = 13;
  /** RegularExpression Id. */
  int VARIABLE = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"E\"",
    "<CONSTANT>",
    "<DIGIT>",
    "<COMPLEX>",
    "<LETTER>",
    "<VARIABLE>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
  };

}
